/* ------------------------------------------------------------------------- */
/*
  Title: MLP PTML3 SIN DOUBLE CARB, Neural Network execution code.
  Automatically generated by SNN, Fri May 26 12:57:40 2023


  License Agreement:
  -----------------

  Copyright StatSoft Inc., 2000-2001, all rights reserved.
  This source code (Source Code Generated by STATISTICA Neural Networks,
  referred to as "CG" below) is owned by StatSoft Inc. and is protected
  by United States Copyright laws and international treaty provisions. You
  shall treat the CG like any copyrighted material.
  The CG may not be redistributed or used except in accordance with the
  conditions below.

  The licensee is granted a license to incorporate the CG as embedded
  software in their own hardware and software products, and to distribute an
  unlimited number of such embedded copies as part of this license subject to
  obtaining prior written consent from StatSoft Inc., and subject to
  the conditions listed below.

  Prior consent is required so that StatSoft Inc. can ensure that license
  conditions are not breached, and can track legitimate use of the CG. Consent
  shall not be refused unless StatSoft Inc. reasonably believes that a
  breach of license conditions will occur. Consent shall usually be granted
  within five working days of the request, providing that sufficient details of
  the intended use are given.

  Requests should be sent to SNN Project Director, StatSoft, Inc.,
  2300 East 14th Street, Tulsa OK 74104 USA, FAX: 918-749-2217,
  E-Mail: info@statsoft.com.

  The licensee may modify the CG as they see fit for embedded use, including
  recoding into alternative programming languages, altering the neural network
  architecture and weights, and otherwise modifying the CG, provided that they
  keep intact this copyright and license notice.

  The licensee may distribute products including the compiled version of CG.

  The licensee shall not:-
    Sublicense, rent, lease, or assign any portion of the CG to third parties.
    Allow compiled versions of the CG to be incorporated in products owned
    by third parties.
    Allow access to the CG to third parties.
    Use (implicitly or explicitly) any reference to StatSoft, Inc., STATISTICA,
    STATISTICA Neural Networks, or any trade names used by StatSoft, Inc.
    to describe, promote, or reference products in which CG is used, or which
    benefit from CG.

  Except as expressly stated herein, the CG is provided "AS IS." The licensee
  shall be entirely responsible for the selection of the CG and for the
  installation, integration, use of, and results obtained from, the CG.
  In particular, but without limitation, attention is drawn to the issue of
  "limited numeric accuracy," which implies that results may not be identical to
  those when executing the same network in STATISTICA Neural Networks or through
  its Application Programming Interface.

  All other warranties or conditions, either express or implied, including but
  not limited to implied warranties of merchantability or fitness for a
  particular purpose, with respect to the CG and written information
  accompanying the CG, are excluded from the license.

  No liability for Consequential Damages. To the maximum extent permitted by
  applicable law, in no event shall StatSoft Inc.,
  or the vendor be liable for any damages whatsoever
  (including, without limitation, damages for loss of profits,
  business interruption, loss of information, or any other pecuniary loss)
  arising out of the use or inability to use this product,
  even if the vendor has been advised of the possibility of
  such damages.

  This license and your right to use the CG shall terminate automatically
  if StatSoft, Inc. determines that you violate any part of the agreement
  or if you violate any part of this agreement without the knowledge of
  StatSoft, Inc. In the event of termination, you shall immediately destroy
  all copies of the CG.

  This agreement constitutes the entire agreement between you and StatSoft Inc.,
  and supersedes any prior agreement concerning the CG. It shall
  not be modified except by written agreement dated subsequent to the date of
  this agreement signed by an authorized representative of StatSoft Inc.
  StatSoft Inc. shall not be bound by any provision of any purchase order,
  confirmation, correspondence, or otherwise, unless StatSoft Inc.
  specifically agrees to the provision in writing.

  This agreement shall be considered as a contract made in the United States
  of America and according to United States Law,
  subject to the exclusive jurisdiction of the United States Courts.
*/
/* standard includes. math.h needed for exp() function. */

#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>

#ifndef FALSE
#define FALSE 0
#define TRUE 1
#endif

#define MENUCODE -999


static double MLP PTML3 SIN DOUBLE CARB02Thresholds[] =
{

/* layer 1 */
-0.15865725212825627, 0.18139304536303297, 0.33702363524478063, 0.67046270618818726,
0.60353786399800724, -0.372816704591444, -0.92926753016823549, 1.0706493262336756,
0.7642434740620877, -1.2342076483228714, -0.46533490993723975, 0.89733898749128571,
-0.56379474319889378, -0.5708613626589385, -0.52918763638496635, -0.76991263679462307,
0.72953366568011868, 0.54522438441968857, 0.2486962688147612, -0.61346288604590982,

/* layer 2 */
0.0024748735461600675, 0.81955528762796814, 0.46062432504479822, 0.946458073941431,
0.41223598189286392, -0.86729950076628848, -0.31556182126673354, -0.52339303742631471,
-0.85091924884952452,

/* layer 3 */
1.0758452273118047

};

static double MLP PTML3 SIN DOUBLE CARB02Weights[] =
{

/* layer 1 */
0.045531219848453874, -0.10858792859941396, 0.81470842169760893, -0.64951737058391457,
-0.71955764511919373, 0.44865746360229669, 0.76254801031504738, -0.63720761638067491,
-0.26115697686643835,
0.40783222688947868, -0.10935672654982194, 0.070216357180398981, 0.69489452206411662,
0.13229946237783402, 0.61834200827315144, 0.58340004705719772, -0.048394808442616823,
0.8754390791650638,
-0.34939331638467747, 0.4659382090524139, -0.43764917358866823, 1.3114310345275366,
0.34874977245793254, 0.25996986421566354, 0.29290466488464056, 0.46998351206507888,
0.79304909880964569,
0.041496082235432864, -0.53331365663712382, -0.085843607077425707, -0.60054436684292578,
-0.17318796601281461, 0.21704592573704265, -0.61548825996870626, 0.47031649681828697,
0.013073992672719834,
-0.60525561111409765, -0.33340814577401368, -0.59486579329468425, -1.0202119143864981,
-0.85948226705292219, 0.34884060230095576, 0.099462015243135235, 0.51682999264266927,
-0.2111565168217775,
-0.90362351928873552, 0.004666723749465476, 0.84407449192462258, 0.057156783784686541,
-0.24679059745587639, 0.1994474000123258, 0.76900334738991083, -0.19394393248600478,
-0.96542519135922533,
-0.44375863548657218, -0.82063803146370184, -0.2085225210493295, 0.53489330581120276,
-0.013791520953109862, -0.1081449837552643, -0.67369217605505505, 0.62185915222648303,
0.46938769373196632,
-0.39203910282221144, 0.34833857198387058, -0.36220219419585009, -0.0033416786654611778,
-0.38778383188281962, -0.52167224777728805, -0.80605310678556263, -0.32962162916256432,
0.28946969616666651,
-0.10402502803395695, 0.055107345129010422, -0.23219568078548017, -0.049718228837486347,
0.38363907295679162, -0.048652132336485493, 0.91685953369595885, 0.5751544722505102,
0.23486184753468059,
-0.02844127083348193, -0.59601391285977257, -0.20433868947934311, -0.39875612629443868,
0.9056472379072007, 0.55317733221366983, 0.70541046211671488, -0.42269103191319518,
-0.058846417510382769,
-0.41351454999138498, 0.98420936683143301, -0.13419501967691144, -0.77109308139412214,
-0.079376222225830767, 0.72078667779543981, 0.45146097621193093, -0.73655720136111436,
0.39808783154600053,
-0.27332510447463082, 0.35936039889992444, -0.50271594549636844, -0.44557474233006472,
0.30217140970479345, -0.55278018281469865, 0.078660776984558881, -0.60067486600314512,
-0.80020357025269417,
-1.2161404685419397, 0.67710057317040395, 0.86640130575090957, 0.038226676208024675,
0.99272949563303581, -0.019641580629090164, -0.46814396163374089, 1.2094411238296483,
-0.40745216952372759,
-0.019371999277632751, 0.14250977978522236, -0.93002493207667758, -0.97987468737981809,
-0.84447574924654101, -0.35793533397780719, -0.74613224245223553, 0.72763121074197501,
0.11901173192582742,
-0.80268298459195864, -0.64944309579498494, 0.11496109414191615, 0.51526861795058565,
0.40023118741169977, -0.91782290408644907, -0.54016721593042849, -0.20496064123114791,
-0.51378311280079503,
-0.049464295158112528, -0.04836238376527225, -0.44707184979794379, -0.73871612090220018,
-0.12361827183713021, -0.60153477795506616, -0.45591884050989451, -0.77849038609230181,
0.3957101491621392,
0.20072508162940242, 0.20844818243331867, 0.30543725053206977, 0.46160623839270454,
-0.24404248609296672, -0.46581439442333394, 0.91161006336234252, -0.26783363820558909,
1.0823172349712396,
0.48488167124371356, -0.63266663924628141, -0.63392953789475193, -1.1931023472435711,
0.38199438855145923, -0.29572380103595808, 0.22537358735553212, 0.027866702556141001,
-0.59641105623093449,
0.18561605244258131, -0.43043355723166093, -0.75108011570393962, -0.57250461342599446,
-0.046768453210707106, 0.80192264350218734, -0.10266105662505247, -0.63441939091684851,
0.82955615500560553,
0.94470001645423818, -0.66192704065514507, -0.18901957166465902, -0.16248580784768096,
-0.13828464816892644, 0.71654444446130361, -0.72726069820360983, -0.2903556866467355,
-0.78911318813194897,

/* layer 2 */
1.1097201153480616, -0.20943831488847489, -0.99201359696255009, 1.2384078444134736,
-0.55341690266776677, 0.83029536315207608, 0.72676903537304516, -0.58512076513477562,
0.23328318040804774, -0.51147073063529003, 0.008366000231830607, -0.47997453277364022,
-0.17492035020009139, 0.022855849655536813, -0.34468479678168606, 0.86140730561269896,
0.44278186514997814, 1.2720805113977363, 0.79550051934277255, -0.39896677165370098,
-0.82930775240024535, 0.026362242839862146, -0.59594762505428078, -0.3227545910215287,
-0.20831247942833081, -0.77339565431240387, -0.15285298600132025, 1.1762551542755932,
0.14706965949589793, -0.15838881645200581, -0.044065855851692426, -1.0009393842591474,
-0.5401896559397833, 1.5683674962025158, -0.48721560466354119, 1.2714723536382313,
-0.81753865191504005, 1.088626681369385, -0.018113809762502344, 0.8497888320471918,
-1.1342940855495109, 0.81222578551886782, 0.16103862627652635, -0.75287949605280102,
0.62540651731995645, -0.35198400301646598, 0.20224727964377878, 0.87806952086378698,
-0.82484901948799172, 0.039620778399404318, -0.139903578170888, -0.71275270369172872,
0.46818290419326603, -1.0345962164730933, -0.4849543118712038, -0.57386858670198349,
-0.10347478623893856, 0.8092943831785504, 0.48519058161520318, -0.15218111228995315,
-0.16285378445185927, 0.15551189725481435, -0.65829973496979899, 0.60650125240225761,
1.1929260174052536, 0.37358441188010044, 0.94091093629398992, -1.1417317958598643,
0.26461898187046767, 0.094973668075508014, 0.902485911896865, -0.48322414153562337,
-0.23832793367734945, 0.59333874924920338, -0.51444891512923385, 0.62553888726759665,
0.56046945052855002, 0.8707939449253348, -0.48548429936452908, -0.37451431575048155,
0.57466698417671158, 0.58094386445422841, 0.54881485447501011, -0.64664516262618543,
-1.0025051114337098, -0.37583309021960265, -0.63430280100992553, 0.93715372574742861,
-0.11505242167178183, 0.50652616002445816, -0.1811513648993657, -1.0996575444842904,
-0.20472012449851409, -1.024583441537366, 0.36128112486133618, -0.58137468575178242,
-0.7573594658025159, 0.97054881414823357, 0.23381983999123881, 0.21277277331152172,
0.96971074701856619, -0.20228595308774952, -0.70725372500338679, -0.45678650592329878,
0.11353763697050484, -0.016944431334699764, -0.2935531394734115, 0.72296796165702859,
-0.56006107421022866, -0.47862619756922115, -0.29606982050398972, 0.53034672083106549,
-0.5486344570249676, 0.73845581078800915, 0.68745188801617729, 1.2852042131853889,
-0.90210364125876996, -0.44628757542722225, -0.17476838868252753, 0.30145612663977495,
0.68974045943183593, -0.56554201906041457, 0.13205842333434412, -0.90168341640865424,
0.73405549975290474, -0.95413957011670802, 0.8337133681880371, 0.93596574795934195,
-0.22596784862607833, 0.03792436432879627, 0.029079527713690902, -0.96034920509086841,
0.20172432569325957, -1.1110333098558762, 0.086583995758545598, -0.73596004990322894,
-0.97293317444578753, -0.9037180235259572, 0.027710342271955408, 0.33083171644811249,
0.48445205830410415, -0.044937095730121987, -0.38033747790325517, 0.58103775998086604,
0.4504403149261989, -0.10766051876210242, 1.0171636163793445, 0.67506620465452238,
-0.46326600606010621, -0.011508921078039228, 0.25431890642610833, 1.0239336147708287,
1.3715941515115679, 1.1776315941160849, 0.5556131923592984, -0.95169438018359309,
-0.44333058013707993, -0.18103581880597561, -0.88359983351626492, 0.8330685953680983,
0.47764251521055906, 0.056526506054833121, -0.66588040290841355, -1.0694350753459412,
-1.1126348989971679, -1.1098627052086392, 0.60642662597776265, -1.2062643504294051,
-0.47300476768002542, 0.25373359665489409, 0.094175225780751659, 0.13314401240638402,
0.70552617498216164, 0.48998000283790044, 0.7089368442285372, -0.88889794587944171,
-0.22320110555090614, 0.78340269074330204, -0.36102875208850815, 0.44225667520906231,

/* layer 3 */
-0.57036404024109577, -0.82412018270823306, -0.5273237093863582, -0.93737711880781416,
0.2489738952841315, 1.0873205026345087, -0.41489300939341661, -1.3267004962672111,
0.26643459276649051

};

static double MLP PTML3 SIN DOUBLE CARB02Acts[78];

/* ---------------------------------------------------------- */
/*
  MLP PTML3 SIN DOUBLE CARB02Run - run neural network MLP PTML3 SIN DOUBLE CARB02

  inputs - the input variables of this network.
  The variable names are listed below, together with each
  variable's offset in the data set at the time code was
  generated (if the variable is then available).
  Variable (Offset)
  (f(vij))ref=<Yld(%)/c0> (2)
  Cat. Met Van der Waals radius (pm)·Cat. Met abs. min qty (µg) (cI) (3)
  DTime (h)(cI) (4)
  DReusability (min)(cI) (5)
  pKa base·Base (Reagent 3) mmol(cII) (6)
  Solvent dipole mom (D)·V Solvent ml (Tot)(cII) (7)
  Sp(Electrophile, reagent1)·Electrophile (Reagent 1) mmol(cII) (8)
  Sv(Nucleophile, reagent2)·Nucleophile (Reagent 2) mmol(cII) (9)
  DTemperature ºC(cII) (10)

*/
/* ---------------------------------------------------------- */

void MLP PTML3 SIN DOUBLE CARB02Run( double inputs[], double outputs[], int outputType )
{
  int i, j, k, u;
  double *w = MLP PTML3 SIN DOUBLE CARB02Weights, *t = MLP PTML3 SIN DOUBLE CARB02Thresholds;

  /* Process inputs - apply pre-processing to each input in turn,
   * storing results in the neuron activations array.
   */

  /* Input 0: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[0] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[0] = 0.806440584355407;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[0] = inputs[0] * 0.012519561815336464 + -0.21439749608763695;

  /* Input 1: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[1] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[1] = 0.48926945584653181;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[1] = inputs[1] * 4.5318185025892335e-005 + 0.63218628078360128;

  /* Input 2: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[2] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[2] = 0.11124655856549819;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[2] = inputs[2] * 0.010471204188481676 + 0.10538394415357766;

  /* Input 3: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[3] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[3] = 0.41433339991677381;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[3] = inputs[3] * 0.054432145103182741 + 0.38683111119995206;

  /* Input 4: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[4] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[4] = 0.31269378900631445;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[4] = inputs[4] * 0.055519900426657921 + 0.31105849509852268;

  /* Input 5: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[5] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[5] = 0.49624275492228653;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[5] = inputs[5] * 0.46082949308755761 + 0.49645390070922135;

  /* Input 6: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[6] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[6] = 0.2373846523129548;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[6] = inputs[6] * 0.18253504672897194 + 0.23682726393812445;

  /* Input 7: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[7] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[7] = 0.20915030560154549;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[7] = inputs[7] * 0.14238199380353561 + 0.20853679229275462;

  /* Input 8: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[8] == -9999 )
    MLP PTML3 SIN DOUBLE CARB02Acts[8] = 0.45641093481870643;
  else
    MLP PTML3 SIN DOUBLE CARB02Acts[8] = inputs[8] * 0.028527370855821129 + 0.45643793369313806;

  /*
   * Process layer 1.
   */

  /* For each unit in turn */
  for ( u=0; u < 20; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the MLP PTML3 SIN DOUBLE CARB02Acts array.
     */

    /* Initialise hidden unit activation to zero */
    MLP PTML3 SIN DOUBLE CARB02Acts[9+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 9; ++i )
      MLP PTML3 SIN DOUBLE CARB02Acts[9+u] += *w++ * MLP PTML3 SIN DOUBLE CARB02Acts[0+i];

    /* Subtract threshold */
    MLP PTML3 SIN DOUBLE CARB02Acts[9+u] -= *t++;

    /* Now apply the hyperbolic activation function, ( e^x - e^-x ) / ( e^x + e^-x ).
     * Deal with overflow and underflow
     */
    if ( MLP PTML3 SIN DOUBLE CARB02Acts[9+u] > 100.0 )
       MLP PTML3 SIN DOUBLE CARB02Acts[9+u] = 1.0;
    else if ( MLP PTML3 SIN DOUBLE CARB02Acts[9+u] < -100.0 )
      MLP PTML3 SIN DOUBLE CARB02Acts[9+u] = -1.0;
    else
    {
      double e1 = exp( MLP PTML3 SIN DOUBLE CARB02Acts[9+u] ), e2 = exp( -MLP PTML3 SIN DOUBLE CARB02Acts[9+u] );
      MLP PTML3 SIN DOUBLE CARB02Acts[9+u] = ( e1 - e2 ) / ( e1 + e2 );
    }
  }

  /*
   * Process layer 2.
   */

  /* For each unit in turn */
  for ( u=0; u < 9; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the MLP PTML3 SIN DOUBLE CARB02Acts array.
     */

    /* Initialise hidden unit activation to zero */
    MLP PTML3 SIN DOUBLE CARB02Acts[29+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 20; ++i )
      MLP PTML3 SIN DOUBLE CARB02Acts[29+u] += *w++ * MLP PTML3 SIN DOUBLE CARB02Acts[9+i];

    /* Subtract threshold */
    MLP PTML3 SIN DOUBLE CARB02Acts[29+u] -= *t++;

    /* Now apply the hyperbolic activation function, ( e^x - e^-x ) / ( e^x + e^-x ).
     * Deal with overflow and underflow
     */
    if ( MLP PTML3 SIN DOUBLE CARB02Acts[29+u] > 100.0 )
       MLP PTML3 SIN DOUBLE CARB02Acts[29+u] = 1.0;
    else if ( MLP PTML3 SIN DOUBLE CARB02Acts[29+u] < -100.0 )
      MLP PTML3 SIN DOUBLE CARB02Acts[29+u] = -1.0;
    else
    {
      double e1 = exp( MLP PTML3 SIN DOUBLE CARB02Acts[29+u] ), e2 = exp( -MLP PTML3 SIN DOUBLE CARB02Acts[29+u] );
      MLP PTML3 SIN DOUBLE CARB02Acts[29+u] = ( e1 - e2 ) / ( e1 + e2 );
    }
  }

  /*
   * Process layer 3.
   */

  /* For each unit in turn */
  for ( u=0; u < 1; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the MLP PTML3 SIN DOUBLE CARB02Acts array.
     */

    /* Initialise hidden unit activation to zero */
    MLP PTML3 SIN DOUBLE CARB02Acts[38+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 9; ++i )
      MLP PTML3 SIN DOUBLE CARB02Acts[38+u] += *w++ * MLP PTML3 SIN DOUBLE CARB02Acts[29+i];

    /* Subtract threshold */
    MLP PTML3 SIN DOUBLE CARB02Acts[38+u] -= *t++;

  }

  /* Type of output required - selected by outputType parameter */
  switch ( outputType )
  {
    /* The usual type is to generate the output variables */
    case 0:


      /* Post-process output 0, numeric linear scaling */
      outputs[0] = ( MLP PTML3 SIN DOUBLE CARB02Acts[38] - 0 ) / 0.010101010101010102;
      break;

    /* type 1 is activation of output neurons */
    case 1:
      for ( i=0; i < 1; ++i )
        outputs[i] = MLP PTML3 SIN DOUBLE CARB02Acts[38+i];
      break;

    /* type 2 is codebook vector of winning node (lowest actn) 1st hidden layer */
    case 2:
      {
        int winner=0;
        for ( i=1; i < 20; ++i )
          if ( MLP PTML3 SIN DOUBLE CARB02Acts[9+i] < MLP PTML3 SIN DOUBLE CARB02Acts[9+winner] )
            winner=i;

        for ( i=0; i < 9; ++i )
          outputs[i] = MLP PTML3 SIN DOUBLE CARB02Weights[9*winner+i];
      }
      break;

    /* type 3 indicates winning node (lowest actn) in 1st hidden layer */
    case 3:
      {
        int winner=0;
        for ( i=1; i < 20; ++i )
          if ( MLP PTML3 SIN DOUBLE CARB02Acts[9+i] < MLP PTML3 SIN DOUBLE CARB02Acts[9+winner] )
            winner=i;

        outputs[0] = winner;
      }
      break;
  }
}

/* ---------------------------------------------------------- */
/*
  MLP PTML3 SIN DOUBLE CARB02RunPadded - run model MLP PTML3 SIN DOUBLE CARB02

  inputs - the input variables, in the same number and order
  as in the data set at the time the code was generated.
  This alternative routine is useful if you want a consistent
  interface for your generated routines, so that the number
  and order of variables is the same for all of them.
  Variables (ones used as inputs marked thus *):
  0)	Yield
  1)	Set
  2)	(f(vij))ref=<Yld(%)/c0> *
  3)	Cat. Met Van der Waals radius (pm)·Cat. Met abs. min qty (µg) (cI) *
  4)	DTime (h)(cI) *
  5)	DReusability (min)(cI) *
  6)	pKa base·Base (Reagent 3) mmol(cII) *
  7)	Solvent dipole mom (D)·V Solvent ml (Tot)(cII) *
  8)	Sp(Electrophile, reagent1)·Electrophile (Reagent 1) mmol(cII) *
  9)	Sv(Nucleophile, reagent2)·Nucleophile (Reagent 2) mmol(cII) *
  10)	DTemperature ºC(cII) *

*/
/* ---------------------------------------------------------- */

void MLP PTML3 SIN DOUBLE CARB02RunPadded( double inputs[], double outputs[], int outputType )
{
  double in[9];

  /* Copy inputs */
  in[0]=inputs[2];
  in[1]=inputs[3];
  in[2]=inputs[4];
  in[3]=inputs[5];
  in[4]=inputs[6];
  in[5]=inputs[7];
  in[6]=inputs[8];
  in[7]=inputs[9];
  in[8]=inputs[10];


  /* Run the network */
  MLP PTML3 SIN DOUBLE CARB02Run( in, outputs, outputType );
}


/*
  Test harness. Compile including this main() procedure, as
  a windows console program or a DOS program, to interactively
  test that the software functions as expected.
*/

void main(void)
{
  int i, outputType=0, noOutputs=1;
  double inputs[9], outputs[9];

  printf( "\n\nMLP PTML3 SIN DOUBLE CARB test harness program. Enter inputs below\n" );
  printf( "Nominal variables should be numbered starting at 1 (0 for missing)\n" );
  printf( "(e.g. if an input is Gender={male,female}, enter 1 for male, 2 for female)\n" );

  /* Infinite (user-breakable) loop for repeated tests */
start_of_loop:
  while ( 1 )
  {
    /* Get the input pattern */
    for ( i=0; i < 9; ++i )
    {
      printf( "Enter value for input %d: ", i+1 );
      scanf( "%lg", & inputs[i] );

      /* Check for sub-menu */
      if ( inputs[i] == MENUCODE )
      {
        printf( "Control menu. Select output style, or exit:\n" );
        printf( "0. Normal output style (output variable)\n" );
        printf( "1. Output layer activations\n" );
        printf( "2. Codebook vector (usual only for Kohonen networks\n" );
        printf( "3. Winning hidden neuron (ditto only Kohonen)\n" );
        printf( "4. Exit program\n" );
        printf( "> " );
        scanf( "%d", & outputType );
        if ( outputType < 0 || outputType > 3 )
        {
          printf( "\nBye.\n" );
          return;
        }
        else
        {
          /* Determine how many outputs there are to display (depends on
           * output type)
           */
          switch ( outputType )
          {
            case 0:
              noOutputs = 1;
              break;

            case 1:
              noOutputs = 1;
              break;

            case 2:
              noOutputs = 9;
              break;

            case 3:
              noOutputs = 1;
              break;
          }
          goto start_of_loop;
        }
      }
    }

    /* Run the neural network */
    MLP PTML3 SIN DOUBLE CARB02Run( inputs, outputs, outputType );

    /* Display the output of the neural network */
    printf( "\n\nOutput of neural network:\n" );

    for ( i=0; i < noOutputs; ++i )
    {
      printf( "Output %d: ", i+1 );
      printf( "%g\n", outputs[i] );
    }

    printf( "\nEnter next input pattern (for control menu inc. exit, enter %d for any input):\n", MENUCODE );
  }
}
